#define BLACK           0x00
#define BLUE            0x01
#define GREEN           0x02
#define CYAN            0x03
#define RED             0x04
#define PURPLE          0x05
#define BROWN           0x06
#define GRAY            0x07
#define DARKGRAY        0x08
#define LIGHT_BLUE      0x09
#define LIGHT_GREEN     0x0A
#define LIGHT_CYAN      0x0B
#define LIGHT_RED       0x0C
#define LIGHT_PURPLE    0x0D
#define YELLOW          0x0E
#define WHITE           0x0F
